version: "3.1"
services:
    web:
        build: .
        ports:
            - "8000:80"
            - "5001:5001"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"