version: '3.4'

services:
    geolocalizador:
        build:
            context: .
            dockerfile: Dockerfile
        image: apigeo-geolocalizador
        ports:
            - 5001:5001
        restart: on-failure 
        command: /bin/sh -c "while sleep 1000; do :; done"       
        depends_on:
            - rabbitmq
    rabbitmq: # login guest:guest
        image: rabbitmq:3.8-management
        container_name: rabbitmq
        hostname: rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            - "5672:5672"
    